#ifndef MONGO_ERRORS_H
#define MONGO_ERRORS_H

#define MIN_ERR_CODE -2000

typedef enum mongo_api_err {
	MONGO_ERR_NULL_PARAMS = MIN_ERR_CODE,
	MONGO_ERR_MEM_ALLOC,
	MONGO_ERR_POOL_PARAMS,
	MONGO_ERR_URI_NEW,
	MONGO_ERR_POOL_NEW,
	MONGO_ERR_POOL_POP,
	MONGO_ERR_COLL_GET,
	MONGO_ERR_COLL_FIND,
	MONGO_ERR_COLL_INSERT,
	MONGO_ERR_COLL_REMOVE,
	MONGO_ERR_COLL_UPDATE,
	MONGO_ERR_TTL_INVALID,
	MONGO_ERR_COLL_INDEX_CREATE
}mongo_api_err_t;

#define MONGO_ERR_STR(code)  #code
#define CASE(code) case code : return MONGO_ERR_STR(code)

#endif
