#NUMA test
#Mohit Singh 16Oct2013
MESSAGE="NUMA test utilities built successfully"
CC=gcc -g3

all:
	$(CC) -o binNuma numaTest.c -lnuma
	@echo "##################################################"
	@echo $(MESSAGE)
	@echo "##################################################"
clean:
	-@rm binNuma
	
